name: GenerateAdlists

on:
    schedule:
        - cron: "17,43 * * * *"

jobs:
    release:
        runs-on: ubuntu-latest
        name: "Generate Adlists"
        steps:
            - uses: actions/checkout@v3
            - name: Update Adlists - Fetching & Combining Hagezi's Native Tracker Blocklists
              run: |
                bash scripts/generateHageziNativeAdblockCombined.sh
            - name: Update Adlists - Combining Several Adblock Pro Blocklists
              run: |
                bash scripts/generateAdblockProCombined.sh nrd30.txt https://gist.githubusercontent.com/rtsfred3/8553b13be1263ccd5c296f5eb512e6e9/raw/nrd30.abp
            - name: Update Adlists - Converting Host files to Adblock Pro files
              run: |
                bash scripts/generateHostToAdblockPro.sh frellwits.swedish.abp.txt https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt
            - name: Commit Changes
              run: |
                git config --global user.name 'Ryan Fredrickson'
                git config --global user.email '2818162+rtsfred3@users.noreply.github.com'
                git commit -am "Updated Adlists"
                git tag "v$(date +'%Y%m%d.%H%M00')"
                git push
