name: GenerateAdlists

on:
    schedule:
        - cron: "10,55 * * * *"

jobs:
    release:
        runs-on: ubuntu-latest
        name: "Generate Adlists"
        steps:
            - uses: actions/checkout@v3
            - name: Update Adlists - Fetching & Combining Hagezi's Native Tracker Blocklists
              run: |
                bash scripts/generateHageziNativeAdblockCombined.sh
            - name: Commit Changes
              run: |
                git config --global user.name 'Ryan Fredrickson'
                git config --global user.email '2818162+rtsfred3@users.noreply.github.com'
                git commit -am "Updated Adlists"
                git tag "v$(date +'%Y%m%d.%H%M00')"
                git push
